### PR TITLE
index.md remake

### PR DESCRIPTION
**Pull request by ItsLuiggiYahoo**
Additions:

- Download links
- Discord links
- About Polytoria

Removed:

- Some phrases.

### CODE REVIEW

**Review by Alyxsqrd — CHANGES_REQUESTED** [review]
Include macOS download link: https://polytoria.com/places/download/macOS

**Review by BrixsterPlanet — CHANGES_REQUESTED** [review]
Contains grammatical inconsistencies and style errors:
- usage of first person pronouns on the docs is prohibited
- do not refer to Polytoria as a "site." It is a game platform.
- discord invite is unnecessary on the docs

**Comment by ItsLuiggiYahoo** [comment]
> Include macOS download link: https://polytoria.com/places/download/macOS

Thank You!

**Comment by ItsLuiggiYahoo** [comment]
> Contains grammatical inconsistencies and style errors:
> - usage of first person pronouns on the docs is prohibited
> - do not refer to Polytoria as a "site." It is a game platform.
> - discord invite is unnecessary on the docs

First , thanks for the feedback! I changed some of the things, here is the new change log

Added:
- MacOS's download link.

Removed:
- Discord section;
- Removed "you and me" line
- "Site" replaced to "gaming platform"

Please let me know if there's something that I need to change.

**Comment by Alyxsqrd** [comment]
Thank you!

**Pull request merged**
