### PR TITLE
Fix misspellings on docs

### PR DESCRIPTION
**Pull request by hawl1**
## PR Summary

Fixes misspellings on the docs (they are even on CONTRIBUTING.md)

### CODE REVIEW

**Comment by StarManTheGamer** [comment]
epic brix fail (he made the contributing page)

**Comment by hawl1** [comment]
> epic brix fail (he made the contributing page)

not related to this topic anyways
image

**Review by Alyxsqrd — APPROVED** [review]

**Comment by Alyxsqrd** [comment]
Thanks

**Comment by indexxing** [comment]
> epic brix fail (he made the contributing page)

I created the CONTRIBUTING.md page lol

**Comment by ItsLuiggiYahoo** [comment]
> > epic brix fail (he made the contributing page)
> 
> I created the CONTRIBUTING.md page lol

epic index fail lmao

**Comment by indexxing** [comment]
> > > epic brix fail (he made the contributing page)
> > 
> > 
> > I created the CONTRIBUTING.md page lol
> 
> "contributers" 😭

thats literally the only spelling mistake, I wrote the entire file. do u expect me to have good spelling and grammar 24/7 sun rise to sun set???

**Comment by hawl1** [comment]
> > > > epic brix fail (he made the contributing page)
> > > 
> > > 
> > > I created the CONTRIBUTING.md page lol
> > 
> > "contributers" 😭
> 
> thats literally the only spelling mistake, I wrote the entire file. do u expect me to have good spelling and grammar 24/7 sun rise to sunset???

Yes because literally every web browser has a spell-checker built in.
anyways lets close this topic its getting freaky

**Comment by ItsLuiggiYahoo** [comment]
It's getting kinda 𝓯𝓻𝓮𝓪𝓴𝔂

Em qua., 24 de abr. de 2024, 14:19, Hawli ***@***.***>
escreveu:

**Pull request merged**
