### PR TITLE
Update client specs

### PR DESCRIPTION
**Pull request by ItsLuiggiYahoo**
Removed old and EOL versions:
- Ubuntu 18.04 & 20.04 EOL -> Ubuntu 22.04 LTS
- I changed CentOS for Fedora because it is not used anymore as a desktop system.
- Added Debian 12, as it is the most recent version;

==== Hardware Changes ===========
- I changed 1gb of RAM to 2gb of RAM because there are almost none laptops with less than 2gb in the market, because he can't handle most of the mainstream apps.

### CODE REVIEW

**Comment by BrixsterPlanet** [comment]
@willemsteller Confirm updated spec requirements

**Comment by ItsLuiggiYahoo** [comment]
Edited the description to explain the changes.

**Comment by BrixsterPlanet** [comment]
> Edited the description to explain the changes.

Regarding the OS version changes, remember that the client spec requirements list the _minimum_ hardware recommended to run Polytoria, _not_ the norm. The OS version changes should only be made if the previous versions are generally incapable of running the client.

I will check with willemsteller to see if this is the case

**Comment by ItsLuiggiYahoo** [comment]
> > Edited the description to explain the changes.
> 
> Regarding the OS version changes, remember that the client spec requirements list the _minimum_ hardware recommended to run Polytoria, _not_ the norm. The OS version changes should only be made if the previous versions are generally incapable of running the client.
> 
> I will check with willemsteller to see if this is the case

Feel free to change anything

**Comment by Alyxsqrd** [comment]
- Minimum OS versions should be Windows 21H1+, macOS Big Sur 11.0+, and Ubuntu 20.04+.
- Minimum CPU should be x64 architecture, not x86.
- Minimum RAM should be 4GB+.

Otherwise, changes lgtm.

**Comment by ItsLuiggiYahoo** [comment]
> - Minimum OS versions should be Windows 21H1+, macOS Big Sur 11.0+, and Ubuntu 20.04+.
> - Minimum CPU should be x64 architecture only, not x86.
> - Minimum RAM should be 4GB+.
> 
> Otherwise, changes lgtm.

Done!

**Pull request merged**
